- name: Validate web server response
  uri:
    url: http://localhost
    return_content: yes
  register: web_response

- name: Check that response contains expected text
  assert:
    that:
      - "'Hello from Ansible-managed NGINX!' in web_response.content"
