- name: Install openssh-server safely
  apt:
    name: openssh-server
    state: present
    dpkg_options: "--force-confold"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    backup: yes
  notify: restart ssh

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  notify: restart ssh
