- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH (port 22)
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP (port 80)
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Set default policy to deny incoming
  community.general.ufw:
    default: deny
    direction: incoming

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled
